version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: exercises-database
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  exercises-backend:
    image: arturfrimu/exercises:020
    ports:
      - "8081:8081"

  exercises-web-app:
    image: arturfrimu/exercises-web-app:020
    ports:
      - "8082:80"
